---
title: "Credit"
author: "Cameron Smith"
date: "10/3/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#Credit Practice
```{r credit}
library(ISLR)
library(dplyr)
library(ggplot2)

str(Credit)

Credit %>%
  group_by(Gender) %>%
  summarize(mean(Balance))

plot(Credit$Gender, Credit$Balance)

Credit %>%
  ggplot(aes(x = Gender, y = Balance)) +
  geom_boxplot()

mod <- lm(Balance ~ Gender, Credit)
mod
summary(mod)

X <- model.matrix(mod)
head(X)

contrasts(Credit$Gender)

##Same thing as lm()
y <- Credit$Balance
betahat <- solve(t(X) %*% X)%*%t(X)%*%y
betahat

Credit %>%
  ggplot(aes(x = Rating, y = Balance, color = Gender)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

Credit %>%
  ggplot(aes(x = Rating, y = Balance, color = Gender)) +
  facet_grid(~Gender) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

mod2 <- lm(Balance ~ ., Credit)
mod2
summary(mod2)

mod3 <- lm(Balance ~ . - Gender - ID - Student, Credit)
mod3
summary(mod3)

Credit %>%
  group_by(Age) %>%
  summarize(mean(Balance))

plot(Credit$Age, Credit$Balance)

Credit %>%
  ggplot(aes(x = Age, y = Balance)) +
  geom_boxplot()

X1 <- model.matrix(mod)
head(X1)

##Same thing as lm()
y <- Credit$Balance
betahat <- solve(t(X1) %*% X1)%*%t(X1)%*%y
betahat

par(mfrow=c(2,2))
plot(mod2)
par(mfrow = c(1,1))

summarymod2 <- summary(mod2)
rsqrd <- summarymod2$adj.r.squared
```

The $R^2{adj} = `r rsqrd`$.

---

````{r label = "fs"}
mod.fs <- lm(Balance ~ 1, data = Credit)
SCOPE <- (~Income + Limit + Rating + Cards + Age + Education + Gender + Student + Married + Ethnicity)
add1(mod.fs, scope = SCOPE, test = "F")
mod.fs <- update(mod.fs, .~. + Rating)
add1(mod.fs, scope = SCOPE, test = "F")
mod.fs <- update(mod.fs, .~. + Income)
add1(mod.fs, scope = SCOPE, test = "F")
mod.fs <- update(mod.fs, .~. + Student)
add1(mod.fs, scope = SCOPE, test = "F")
mod.fs <- update(mod.fs, .~. + Limit)
add1(mod.fs, scope = SCOPE, test = "F")
mod.fs <- update(mod.fs, .~. + Cards)
add1(mod.fs, scope = SCOPE, test = "F")
mod.fs <- update(mod.fs, .~. + Age)
add1(mod.fs, scope = SCOPE, test = "F")
mod.fs <- update(mod.fs, .~. + Gender)
add1(mod.fs, scope = SCOPE, test = "F")
````

---


````{r label = "be"}
mod.be <- lm(Balance ~ ., data = Credit)
drop1(mod.be, test = "F")
mod.be <- update(mod.be, .~. - Education)
drop1(mod.be, test = "F")
mod.be <- update(mod.be, .~. - Ethnicity)
drop1(mod.be, test = "F")
mod.be <- update(mod.be, .~. - Married)
drop1(mod.be, test = "F")
mod.be <- update(mod.be, .~. - ID)
drop1(mod.be, test = "F")
mod.be <- update(mod.be, .~. - Gender)
drop1(mod.be, test = "F")
mod.be <- update(mod.be, .~. - Education)
drop1(mod.be, test = "F")
mod.be <- update(mod.be, .~. - Age)
drop1(mod.be, test = "F")
mod.be <- update(mod.be, .~. - Rating)
drop1(mod.be, test = "F")
mod.be <- update(mod.be, .~. - Cards)
drop1(mod.be, test = "F")
````

```{r}
library(MASS)
stepAIC(lm(Balance ~ 1, data = Credit), scope = SCOPE, direction = "forward", test = "F")

stepAIC(lm(Balance ~ ., data = Credit), direction = "backward", test = "F")
```